(code)_Projeck__Website__Billiards__Python__Flask/routes/quan_ly_nhan_vien.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask import request
from flask import flash
from database import get_db_connection

nhanvien_blueprint = Blueprint('quan_ly_nhan_vien', __name__)

@nhanvien_blueprint.route('/quanlynhanvien')



#----------------QUẢN LÝ NHÂN VIÊN----------------------
@nhanvien_blueprint.route('/quanlynhanvien')
def quanlynhanvien():
    
    keyword = request.args.get('keyword', '')

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    if keyword:
        cursor.execute("SELECT a.* FROM account a JOIN role r ON a.role_id = r.id WHERE r.id = 2 AND (a.full_name LIKE %s OR a.phone_number LIKE %s)", ('%' + keyword + '%', '%' + keyword + '%'))
    else:
        cursor.execute("SELECT a.* FROM account a JOIN role r ON a.role_id = r.id WHERE r.id = 2 ")

    nhanviens = cursor.fetchall()

    cursor.close()
    connection.close()

    return render_template('quan_li_nhan_vien/nhanvien.html', nhanviens=nhanviens)
#THÊM NHÂN VIÊN
@nhanvien_blueprint.route('/themnhanvien', methods=['GET', 'POST'])
def them_nhan_vien():
    
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        full_name = request.form['full_name']
        phone_number = request.form['phone_number']
        address = request.form['address']
        role_id = 2
        
        connection = get_db_connection()
        cursor = connection.cursor()

        insert_query = "INSERT INTO account (username, password,full_name,phone_number,address,role_id) VALUES (%s, %s, %s, %s, %s, %s)"
        cursor.execute(insert_query, (username, password,full_name,phone_number,address,role_id))
        connection.commit()

        cursor.close()
        connection.close()

        flash('Nhân viên mới đã được thêm thành công!', 'success')
        return redirect(url_for('quan_ly_nhan_vien.quanlynhanvien'))
    return render_template('quan_li_nhan_vien/them_nhan_vien.html')

#SỬA NHÂN VIÊN
@nhanvien_blueprint.route('/sua_nhan_vien/<int:id>', methods=['GET', 'POST'])
def sua_nhan_vien(id):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        full_name = request.form['full_name']
        phone_number = request.form['phone_number']
        address = request.form['address']
        
        update_query = """
            UPDATE account 
            SET username = %s, password = %s, full_name = %s, phone_number = %s, address = %s 
            WHERE id = %s
        """
        cursor.execute(update_query, (username, password, full_name, phone_number, address, id))
        
        # Nếu có bảng lương, cập nhật thông tin lương của nhân viên tại đây
        # Ví dụ: update_salary(id, salary_info)
        
        connection.commit()
        
        flash('Thông tin nhân viên đã được cập nhật!', 'success')
        return redirect(url_for('quan_ly_nhan_vien.quanlynhanvien'))
    
    cursor.execute("SELECT * FROM account WHERE id = %s", (id,))
    nhanvien = cursor.fetchone()
    
    cursor.close()
    connection.close()
    
    return render_template('quan_li_nhan_vien/sua_nhan_vien.html', nhanvien=nhanvien)
# XÓA NHÂN VIÊN
@nhanvien_blueprint.route('/quan_ly_nhan_vien.xoanhanvien/<int:id>', methods=['GET', 'POST'])
def xoa_nhan_vien(id):
    connection = get_db_connection()
    cursor = connection.cursor()

    try:
        # Kiểm tra và xóa các bản ghi liên quan trong bảng salary
        delete_salary_query = "DELETE FROM luong WHERE account_id = %s"
        cursor.execute(delete_salary_query, (id,))
        ## Kiểm tra và xóa các bản ghi liên quan trong bảng penalty
        delete_penalty_query = "DELETE FROM ca_lam_viec WHERE account_id = %s"
        cursor.execute(delete_penalty_query, (id,))
        
     
        # Tiếp tục xóa nhân viên từ bảng account
        delete_query_account = "DELETE FROM account WHERE id = %s"
        cursor.execute(delete_query_account, (id,))
        
        connection.commit()

        flash(f'Nhân Viên có ID {id} đã được xóa thành công!', 'success')
    except Exception as e:
        flash(f'Đã xảy ra lỗi khi xóa nhân viên: {str(e)}', 'error')
        connection.rollback()
    finally:
        cursor.close()
        connection.close()

    return redirect(url_for('quan_ly_nhan_vien.quanlynhanvien'))



#----------------------------
@nhanvien_blueprint.route('/phan_cong_viec')
def phan_cong_viec():
    conn = get_db_connection()
    cursor = conn.cursor()
    
    cursor.execute("""
        SELECT 
            clv.id,
            a.full_name, 
            clv.cong_viec, 
            clv.ngay_ca_lam, 
            clv.gio_bat_dau, 
            clv.gio_ket_thuc, 
            p.ly_do, 
            p.so_tien_phat
        FROM ca_lam_viec clv
        JOIN account a ON clv.account_id = a.id
        LEFT JOIN phat p ON clv.phat_id = p.id
    """)
    
    thong_tin = cursor.fetchall()
    
    cursor.close()
    conn.close()
    
    return render_template('quan_li_nhan_vien/phan_cong_viec.html', thong_tin=thong_tin)
@nhanvien_blueprint.route('/them_cong_viec', methods=['GET', 'POST'])
def them_cong_viec():
    if request.method == 'POST':
        account_id = request.form['account_id']
        cong_viec = request.form['cong_viec']
        ngay_ca_lam = request.form['ngay_ca_lam']
        gio_bat_dau = request.form['gio_bat_dau']
        gio_ket_thuc = request.form['gio_ket_thuc']
        
        try:
            conn = get_db_connection()
            cursor = conn.cursor()
            
            # Thực hiện INSERT vào bảng ca_lam_viec
            query = "INSERT INTO ca_lam_viec (account_id, cong_viec, ngay_ca_lam, gio_bat_dau, gio_ket_thuc) VALUES (%s, %s, %s, %s, %s)"
            cursor.execute(query, (account_id, cong_viec, ngay_ca_lam, gio_bat_dau, gio_ket_thuc))
            
            conn.commit()
            flash('Thêm công việc mới thành công', 'success')
            
        except mysql.connector.Error as e: # type: ignore
            print(f'Error: {e}')
            flash('Thêm công việc mới thất bại', 'error')
            
        finally:
            cursor.close()
            conn.close()
            
        return redirect(url_for('quan_ly_nhan_vien.phan_cong_viec'))
    
    # Lấy danh sách tài khoản để hiển thị trong dropdown
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT id, full_name FROM account")
    accounts = cursor.fetchall()
    cursor.close()
    conn.close()
    
    return render_template('quan_li_nhan_vien/them_cong_viec.html', accounts=accounts)
@nhanvien_blueprint.route('/sua_cong_viec/<int:id>', methods=['GET', 'POST'])
def sua_cong_viec(id):
    if request.method == 'POST':
        account_id = request.form['account_id']
        cong_viec = request.form['cong_viec']
        ngay_ca_lam = request.form['ngay_ca_lam']
        gio_bat_dau = request.form['gio_bat_dau']
        gio_ket_thuc = request.form['gio_ket_thuc']
        phat_id = request.form['phat_id'] if request.form['phat_id'] else None

        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            # Thực hiện UPDATE vào bảng ca_lam_viec
            query = """
                UPDATE ca_lam_viec 
                SET account_id = %s, cong_viec = %s, ngay_ca_lam = %s, gio_bat_dau = %s, gio_ket_thuc = %s, phat_id = %s 
                WHERE id = %s
            """
            cursor.execute(query, (account_id, cong_viec, ngay_ca_lam, gio_bat_dau, gio_ket_thuc, phat_id, id))

            conn.commit()
            flash('Cập nhật công việc thành công', 'success')

        except mysql.connector.Error as e: # type: ignore
            print(f'Error: {e}')
            flash('Cập nhật công việc thất bại', 'error')

        finally:
            cursor.close()
            conn.close()

        return redirect(url_for('quan_ly_nhan_vien.phan_cong_viec'))

    # Lấy thông tin công việc để hiển thị trong form
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("SELECT account_id, cong_viec, ngay_ca_lam, gio_bat_dau, gio_ket_thuc, phat_id FROM ca_lam_viec WHERE id = %s", (id,))
    cong_viec = cursor.fetchone()

    cursor.execute("SELECT id, full_name FROM account")
    accounts = cursor.fetchall()

    cursor.execute("SELECT id, ly_do FROM phat")
    phat = cursor.fetchall()

    cursor.close()
    conn.close()

    return render_template('quan_li_nhan_vien/sua_cong_viec.html', id=id, cong_viec=cong_viec, accounts=accounts, phat=phat)


@nhanvien_blueprint.route('/quan_ly_nhan_vien.xoa_cong_viec/<int:id>', methods=['POST'])
def xoa_cong_viec(id):
    
    if request.method == 'POST':
        try:
            conn = get_db_connection()
            cursor = conn.cursor()

            # Thực hiện DELETE từ bảng ca_lam_viec
            query = "DELETE FROM ca_lam_viec WHERE id = %s"
            cursor.execute(query, (id,))

            conn.commit()
            flash('Xóa công việc thành công', 'success')

        except mysql.connector.Error as e: # type: ignore
            print(f'Error: {e}')
            flash('Xóa công việc thất bại', 'error')

        finally:
            cursor.close()
            conn.close()

        return redirect(url_for('quan_ly_nhan_vien.phan_cong_viec'))

    # Các xử lý khác khi request.method là GET hoặc những phương thức khác
    return redirect(url_for('quan_ly_nhan_vien.phan_cong_viec'))


@nhanvien_blueprint.route('/tim_kiem_cong_viec', methods=['GET', 'POST'])
def tim_kiem_cong_viec():
    if request.method == 'POST':
        search_term = request.form['search_term']
        conn = get_db_connection()
        cursor = conn.cursor()

        # Tìm kiếm các bản ghi trong bảng ca_lam_viec
        query = """

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/nhanvien.html
<!-- quanlynhanvien.html -->
{% extends 'base.html' %}

{% block title %}
    Quản Lí Nhân Viên
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/nhanvien.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
    <script>
        function validateSearchForm(event) {
            const searchInput = document.querySelector('input[name="keyword"]');
            if (searchInput.value.trim() === '') {
                alert('Vui lòng nhập từ khóa tìm kiếm');
                event.preventDefault(); // Ngăn chặn form submit
            }
        }
    </script>

{% endblock %}

{% block content %}
    <h1>Quản lý Nhân Viên</h1>
    
    <div class="action-links">
        <a href="/themnhanvien">Thêm Nhân Viên mới</a>
        <a href="/phan_cong_viec">Phân công việc</a>
    </div>

    <!-- Form tìm kiếm -->
    <div class="search-container">
        <form action="{{ url_for('quan_ly_nhan_vien.quanlynhanvien') }}" method="GET" class="search-form" onsubmit="validateSearchForm(event)">
            <input type="text" name="keyword" placeholder="Nhập từ khóa tìm kiếm...">
            <button type="submit">Tìm kiếm</button>
        </form>
    </div>

    <table>
        <thead>
            <tr>
                <th>Mã Đăng Nhập</th>
                <th>Tên Đăng Nhập</th>
                <th>Mật Khẩu</th>
                <th>Họ Tên</th>
                <th>Số điện thoại</th>
                <th>Địa chỉ</th>
                <th>Tùy chọn</th>
            </tr>
        </thead>
        <tbody>
            {% for nhanvien in nhanviens %}
            <tr>
                <td>{{ nhanvien.id }}</td>
                <td>{{ nhanvien.username }}</td>
                <td>{{ nhanvien.password }}</td>
                <td>{{ nhanvien.full_name }}</td>
                <td>{{ nhanvien.phone_number }}</td>
                <td>{{ nhanvien.address }}</td>
                <td>
                    <a href="{{ url_for('quan_ly_nhan_vien.sua_nhan_vien', id=nhanvien.id) }}" class="edit-button">Sửa</a>
                    <a href="/quan_ly_nhan_vien.xoanhanvien/{{ nhanvien.id }}" class="delete-button" onclick="return confirm('Bạn có chắc muốn xóa nhân viên này?')">Xóa</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="action-links">
        <a href="/tong_luong_thang">Tổng lương tháng</a>
        <a href="/tong_luong_nam">Tổng Lương Năm</a>   
    </div>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/phan_cong_viec.html
{% extends 'base.html' %}

{% block title %}
    Phân công việc
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/phan_cong_viec.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
    <h1>Thông tin công việc và phạt</h1>

    <table>
        <thead>
            <tr>
                <th>Họ và tên</th>
                <th>Công việc</th>
                <th>Ngày làm</th>
                <th>Giờ bắt đầu</th>
                <th>Giờ kết thúc</th>
                <th>Lý do phạt</th>
                <th>Số tiền phạt</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            {% for row in thong_tin %}
                <tr>
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td>
                    <td>{{ row[6] }}</td>
                    <td>{{ row[7] }}</td>
                    <td>
                        <form action="{{ url_for('quan_ly_nhan_vien.xoa_cong_viec', id=row[0]) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <button type="submit" class="btn btn-danger" onclick="return confirm('Bạn có chắc muốn xóa công việc này?')">Xóa</button>
                          </form>
                        <a href="{{ url_for('quan_ly_nhan_vien.sua_cong_viec', id=row[0]) }}" class="edit-button">Sửa</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="action-links">
    <a href="{{ url_for('quan_ly_nhan_vien.them_cong_viec') }}">Thêm công việc mới</a>
    <a href="{{ url_for('quan_ly_nhan_vien.tim_kiem_cong_viec') }}">Tìm Kiếm</a>
    </div>
    <a href="/quanlynhanvien" class="back-button">Quay lại</a>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/sua_cong_viec.html
{% extends 'base.html' %}

{% block title %}
    Sửa công việc
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/sua_cong_viec.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
    <h1>Sửa công việc</h1>
    
    <form method="POST" action="{{ url_for('quan_ly_nhan_vien.sua_cong_viec', id=id) }}">
        <label for="account_id">Nhân viên:</label>
        <select id="account_id" name="account_id" required>
            {% for account in accounts %}
                <option value="{{ account[0] }}" {% if account[0] == cong_viec[0] %}selected{% endif %}>{{ account[1] }}</option>
            {% endfor %}
        </select><br><br>
        
        <label for="cong_viec">Công việc:</label>
        <input type="text" id="cong_viec" name="cong_viec" value="{{ cong_viec[1] }}" required><br><br>
        
        <label for="ngay_ca_lam">Ngày làm:</label>
        <input type="date" id="ngay_ca_lam" name="ngay_ca_lam" value="{{ cong_viec[2] }}" required><br><br>
        
        <label for="gio_bat_dau">Giờ bắt đầu:</label>
        <input type="time" id="gio_bat_dau" name="gio_bat_dau" value="{{ cong_viec[3] }}" required><br><br>
        
        <label for="gio_ket_thuc">Giờ kết thúc:</label>
        <input type="time" id="gio_ket_thuc" name="gio_ket_thuc" value="{{ cong_viec[4] }}" required><br><br>
        
        <label for="phat_id">Lý do phạt (nếu có):</label>
        <select id="phat_id" name="phat_id">
            <option value="">Không có</option>
            {% for p in phat %}
                <option value="{{ p[0] }}" {% if p[0] == cong_viec[5] %}selected{% endif %}>{{ p[1] }}</option>
            {% endfor %}
        </select><br><br>
        
        <button type="submit">Cập nhật công việc</button>
    </form>
    
    <a href="{{ url_for('quan_ly_nhan_vien.phan_cong_viec') }}" class="back-button">Quay lại</a>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/sua_nhan_vien.html
<!-- sua_nhan_vien.html -->
{% extends 'base.html' %}

{% block title %}
    Sửa Nhân Viên
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/sua_nhan_vien.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}


{% block content %}
<div class="container">
        <h2>Sửa Nhân Viên </h2>



<form action="{{ url_for('quan_ly_nhan_vien.sua_nhan_vien', id=nhanvien.id) }}" method="POST">
  
    <div class="form-group">
        <label for="username">Tên Đăng Nhập:</label>
        <input type="text" id="username" name="username" value="{{ nhanvien.username }}" required>
    </div>
    <div class="form-group">
        <label for="password">Mật Khẩu:</label>
        <input type="text" id="password" name="password" value="{{ nhanvien.password }}" required>
    </div>


    <div class="form-group">
        <label for="full_name">Họ Tên:</label>
        <input type="text" id="full_name" name="full_name" value="{{ nhanvien.full_name }}" required>
    </div>

    <div class="form-group">
        <label for="phone_number">Số điện thoại:</label>
        <input type="number" id="phone_number" name="phone_number" value="{{ nhanvien.phone_number }}" required>
    </div>

    <div class="form-group">
        <label for="address">Địa chỉ:</label>
        <input type="text" id="address" name="address" value="{{ nhanvien.address }}" required>
    </div>

    
    <div class="form-group">
        <button type="submit">Lưu Thay Đổi</button>
        <a href="/quanlynhanvien" class="back-button">Quay lại</a>

    </div>
</div>
</form>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/them_cong_viec.html
{% extends 'base.html' %}

{% block title %}
    Thêm công việc mới
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/sua_cong_viec.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
    <h1>Thêm công việc mới</h1>
    
    <form method="POST" action="{{ url_for('quan_ly_nhan_vien.them_cong_viec') }}">
        <label for="account_id">Nhân viên:</label>
        <select id="account_id" name="account_id" required>
            {% for account in accounts %}
                <option value="{{ account[0] }}">{{ account[1] }}</option>
            {% endfor %}
        </select><br><br>
        
        <label for="cong_viec">Công việc:</label>
        <input type="text" id="cong_viec" name="cong_viec" required><br><br>
        
        <label for="ngay_ca_lam">Ngày làm:</label>
        <input type="date" id="ngay_ca_lam" name="ngay_ca_lam" required><br><br>
        
        <label for="gio_bat_dau">Giờ bắt đầu:</label>
        <input type="time" id="gio_bat_dau" name="gio_bat_dau" required><br><br>
        
        <label for="gio_ket_thuc">Giờ kết thúc:</label>
        <input type="time" id="gio_ket_thuc" name="gio_ket_thuc" required><br><br>
        
        <button type="submit">Thêm công việc</button>
    </form>
    
    <a href="{{ url_for('quan_ly_nhan_vien.phan_cong_viec') }}" class="back-button">Quay lại</a>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/them_nhan_vien.html
<!-- them_nhan_vien.html -->
{% extends 'base.html' %}

{% block title %}
    Thêm Nhân Viên
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/them_nhan_vien.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
    <div class="container">
        <h2>Thêm Nhân Viên mới</h2>
        <form method="post">
            <label for="username">Tên Đăng Nhập:</label>
            <input type="text" id="username" name="username" required
                   pattern="^[a-zA-Z0-9]{6,}$"
                   title="Tên đăng nhập phải có ít nhất 6 ký tự và chỉ chấp nhận chữ cái và số">

            <label for="password">Mật Khẩu:</label>
            <input type="text" id="password" name="password" required
                   pattern="^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$"
                   title="Mật khẩu phải có ít nhất 8 ký tự, bao gồm ít nhất một chữ hoa, một chữ thường, một số và một ký tự đặc biệt">

            <label for="full_name">Họ Tên:</label>
            <input type="text" id="full_name" name="full_name" required>

            <label for="phone_number">Số điện thoại:</label>
            <input type="number" id="phone_number" name="phone_number" required>

            <label for="address">Địa chỉ:</label>
            <input type="text" id="address" name="address" required>

            <input type="submit" value="Thêm Nhân Viên">
        </form>
        <a href="/quanlynhanvien" class="back-button">Quay lại</a>
    </div>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/tim_kiem_cong_viec.html
{% extends 'base.html' %}

{% block title %}
    Tìm kiếm công việc
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/phan_cong_viec.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
    <h1>Tìm kiếm công việc</h1>
    
    <form method="POST" action="{{ url_for('quan_ly_nhan_vien.tim_kiem_cong_viec') }}">
        <label for="search_term">Từ khóa:</label>
        <input type="text" id="search_term" name="search_term" required>
        <button type="submit">Tìm kiếm</button>
    </form>
    
    <table>
        <thead>
            <tr>
                <th>Họ và tên</th>
                <th>Công việc</th>
                <th>Ngày làm</th>
                <th>Giờ bắt đầu</th>
                <th>Giờ kết thúc</th>
                <th>Lý do phạt</th>
                <th>Số tiền phạt</th>
                <th>Chức năng</th>
            </tr>
        </thead>
        <tbody>
            {% for row in thong_tin %}
                <tr>
                    <td>{{ row[0] }}</td>
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td>
                    <td>{{ row[6] }}</td>
                    <td><a href="{{ url_for('quan_ly_nhan_vien.sua_cong_viec', id=row[7]) }}">Sửa</a> | <a href="{{ url_for('quan_ly_nhan_vien.xoa_cong_viec', id=row[7]) }}" onclick="return confirm('Bạn có chắc muốn xóa?')">Xóa</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <a href="{{ url_for('quan_ly_nhan_vien.phan_cong_viec') }}" class="back-button">Quay lại</a>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/tong_luong_nam.html
{% extends 'base.html' %}

{% block title %}
Tổng lương năm
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/tong_luong_nam.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  

</head>
<body>
    <h1>Tổng lương theo năm</h1>

    <table>
        <thead>
            <tr>
                <th>Account ID</th>
                <th>Tên Nhân Viên</th>
                <th>Năm</th>
                <th>Tổng lương cơ bản</th>
                <th>Tổng Thưởng</th>
                <th>Tổng tiền phạt</th>
                <th>Tổng lương</th>
            </tr>
        </thead>
        <tbody>
            {% for row in tong_luong_nam %}
                <tr>
                    <td>{{ row[0] }}</td>
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td>
                    <td>{{ row[6] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="/quanlynhanvien" class="back-button">Quay lại</a>
</body>
</html>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_nhan_vien/tong_luong_thang.html
{% extends 'base.html' %}

{% block title %}
Tổng lương tháng
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_nhan_vien/tong_luong_thang.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tổng lương theo tháng</title>

</head>
<body>
    <h1>Tổng lương tháng</h1>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Account ID</th>
                <th>Tháng</th>
                <th>Năm</th>
                <th>Lương cơ bản</th>
                <th>Thưởng</th>
                <th>Tổng phạt tháng</th>
                <th>Tổng lương</th>
            </tr>
        </thead>
        <tbody>
            {% for row in tong_luong_thang %}
                <tr>
                    <td>{{ row[0] }}</td>
                    <td>{{ row[1] }}</td>
                    <td>{{ row[2] }}</td>
                    <td>{{ row[3] }}</td>
                    <td>{{ row[4] }}</td>
                    <td>{{ row[5] }}</td>
                    <td>{{ row[7] }}</td>
                    <td>{{ row[6] }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="/quanlynhanvien" class="back-button">Quay lại</a>
</body>
</html>
{% endblock %}