(code)_Projeck__Website__Billiards__Python__Flask/routes/quan_ly_san_pham.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask import request
from flask import flash
from database import get_db_connection

sanpham_blueprint = Blueprint('quan_ly_san_pham', __name__)

@sanpham_blueprint.route('/quanlysanpham')






#----------------QUẢN LÝ SẢN PHẨM----------------------
@sanpham_blueprint.route('/quanlysanpham')
def quanlysanpham():
    
    keyword = request.args.get('keyword', '')

    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)

    if keyword:
        cursor.execute("SELECT * FROM sanpham WHERE (TenSP LIKE %s)", ('%' + keyword + '%',))
    else:
        cursor.execute("SELECT * FROM sanpham")

    sanphams = cursor.fetchall()

    cursor.close()
    connection.close()

    return render_template('quan_li_san_pham/sanpham.html', sanphams=sanphams)

#THÊM SẢN PHẨM
@sanpham_blueprint.route('/themsanpham', methods=['GET', 'POST'])
def them_san_pham():
    
    
    if request.method == 'POST':
  
        TenSP = request.form['TenSP']
        Gia = request.form['Gia']
        SoLuong = request.form['SoLuong']
        
        connection = get_db_connection()
        cursor = connection.cursor()

        insert_query = "INSERT INTO sanpham (TenSP, Gia, SoLuong) VALUES (%s, %s, %s)"
        cursor.execute(insert_query, (TenSP, Gia, SoLuong))
        connection.commit()

        cursor.close()
        connection.close()

        flash('Sản phẩm mới đã được thêm thành công!', 'success')
        return redirect(url_for('quan_ly_san_pham.quanlysanpham'))
    return render_template('quan_li_san_pham/them_san_pham.html')

#SỬA SẢN PHẨM
@sanpham_blueprint.route('/suasanpham/<int:MaSP>', methods=['GET', 'POST'])
def sua_san_pham(MaSP):
    connection = get_db_connection()
    cursor = connection.cursor(dictionary=True)
    
    if request.method == 'POST':
        TenSP = request.form['TenSP']
        Gia = request.form['Gia']
        SoLuong = request.form['SoLuong']
        update_query = "UPDATE sanpham SET TenSP = %s, Gia = %s, SoLuong = %s WHERE MaSP = %s"
        cursor.execute(update_query, (TenSP, Gia, SoLuong, MaSP))
        connection.commit()
        
        flash('Thông tin sản phẩm đã được cập nhật!', 'success')
        return redirect(url_for('quan_ly_san_pham.quanlysanpham'))
    
    cursor.execute("SELECT * FROM sanpham WHERE MaSP = %s", (MaSP,))
    sanpham = cursor.fetchone()
    
    cursor.close()
    connection.close()
    
    return render_template('quan_li_san_pham/sua_san_pham.html', sanpham=sanpham)
@sanpham_blueprint.route('/xoasanpham/<int:MaSP>', methods=['GET', 'POST'])
def xoa_san_pham(MaSP):
    connection = get_db_connection()
    cursor = connection.cursor()

    cursor.execute("SELECT * FROM sanpham WHERE MaSP = %s", (MaSP,))
    sanpham = cursor.fetchone()

    if sanpham:
        delete_query = "DELETE FROM sanpham WHERE MaSP = %s"
        cursor.execute(delete_query, (MaSP,))
        connection.commit()

        flash(f'Sản phẩm có ID {MaSP} đã được xóa thành công!', 'success')
    else:
        flash(f'Sản phẩm có ID {MaSP} không tồn tại.', 'error')

    cursor.close()
    connection.close()

    return redirect(url_for('quan_ly_san_pham.quanlysanpham'))

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_san_pham/sanpham.html
<!-- quanlysanpham.html -->
{% extends 'base.html' %}

{% block title %}
    Quản Lí Sản Phẩm
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_san_pham/sanpham.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
    <script>
        function validateSearchForm(event) {
            const searchInput = document.querySelector('input[name="keyword"]');
            if (searchInput.value.trim() === '') {
                alert('Vui lòng nhập từ khóa tìm kiếm');
                event.preventDefault(); // Ngăn chặn form submit
            }
        }
    </script>

{% endblock %}

{% block content %}
    <h1>Quản lý Sản phẩm</h1>
    <div class="action-links">
        <a href="{{ url_for('quan_ly_san_pham.them_san_pham') }}">Thêm sản phẩm mới</a>
    </div>
    <div class="search-form">
        <form method="GET" action="{{ url_for('quan_ly_san_pham.quanlysanpham') }}" onsubmit="validateSearchForm(event)">
            <input type="text" name="keyword" placeholder="Tìm kiếm sản phẩm">
            <button type="submit">Tìm kiếm</button>
        </form>
    </div>
    <table>
        <thead>
            <tr>
                <th>Mã Sản Phẩm</th>
                <th>Tên Sản Phẩm</th>
                <th>Giá</th>
                <th>Số lượng</th>
                <th>Tùy chọn</th>
            </tr>
        </thead>
        <tbody>
            {% for product in sanphams %}
            <tr>
                <td>{{ product.MaSP }}</td>
                <td>{{ product.TenSP }}</td>
                <td>{{ product.Gia }}</td>
                <td>{{ product.SoLuong }}</td>
                <td>
                    <a href="{{ url_for('quan_ly_san_pham.sua_san_pham', MaSP=product.MaSP) }}" class="edit-button">Sửa</a>
                    <a href="{{ url_for('quan_ly_san_pham.xoa_san_pham', MaSP=product.MaSP) }}" class="delete-button" onclick="return confirm('Bạn có chắc muốn xóa sản phẩm này?')">Xóa</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_san_pham/sua_san_pham.html
{% extends 'base.html' %}

{% block title %}
    Sửa Sản Phẩm
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_san_pham/sua_san_pham.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Sửa thông tin sản phẩm</h1>
    <form method="POST" action="{{ url_for('quan_ly_san_pham.sua_san_pham', MaSP=sanpham.MaSP) }}">
        <label for="TenSP">Tên SP:</label>
        <input type="text" id="TenSP" name="TenSP" value="{{ sanpham.TenSP }}"><br>
        <label for="Gia">Giá:</label>
        <input type="number" id="Gia" name="Gia" value="{{ sanpham.Gia }}"><br>
        <label for="SoLuong">Số Lượng:</label>
        <input type="number" id="SoLuong" name="SoLuong" value="{{ sanpham.SoLuong }}"><br>
        <button type="submit">Cập nhật</button>
        <a href="/quanlysanpham" class="back-button">Quay lại</a>

    </form>
</div>
{% endblock %}

(code)_Projeck__Website__Billiards__Python__Flask/templates/quan_li_san_pham/them_san_pham.html
{% extends 'base.html' %}

{% block title %}
    Thêm Sản Phẩm
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/css_san_pham/them_san_pham.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/admin.css') }}">
{% endblock %}

{% block content %}
<div class="form-container">
    <h1>Thêm sản phẩm mới</h1>
    <form method="POST" action="{{ url_for('quan_ly_san_pham.them_san_pham') }}">
        <label for="TenSP">Tên SP:</label>
        <input type="text" id="TenSP" name="TenSP"><br>
        <label for="Gia">Giá:</label>
        <input type="number" id="Gia" name="Gia"><br>
        <label for="SoLuong">Số Lượng:</label>
        <input type="number" id="SoLuong" name="SoLuong"><br>
        <button type="submit">Thêm sản phẩm</button>
    </form>
    <a href="/quanlysanpham" class="back-button">Quay lại</a>

</div>
{% endblock %}